import Footer from '../components/Footer'
import Navbar from '../components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
async function fetchProduct(id){
  const res = await fetch(`https://dummyjson.com/products/${id}`, {
  cache: "no-store"
})
  return res.json();
}
export async function generateMetadata({params}){
  const product = await fetchProduct(params.id)
  return{
      title: product.title,
      description: product.description,
      thumbnail: product.images[1],
      MediaMetadata: new URL('https://istad.co'),
      alternates:{
          canonical: '/',
          languages:{
              'en-US': '/en-US',
              'de-DE': '/de-DE',
          },
      },
      openGraph:{
          images: product.images[0],
          title: product.title,
          description: product.description
      },
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Navbar/>
          {children}
        <Footer/>
        </body>
    </html>
  )
}
