
import Products from "./products/page"


export const metadata = {
  title: 'Ecommerce',
  description: 'Generated by create next app',
}

export default async function Home() {
  return (
    <main className="flex min-h-screen flex-row items-center justify-between p-24">
       <div className="flex flex-row flex-wrap justify-between">
         <Products/>
      </div>
    </main>
  )
}
